@startuml
actor user
participant system
participant pg
participant redis
participant tdm

user -> system : 新增业务监控配置
system -> system : 检查数据的合法性
system -> pg: 落库
system -> redis: 将当前的时间戳更新到redis作为收到客户端的心跳时间，并更新redis中客户端心跳超时的时间
tdm -> tdm : tdm抢到ACTIVE之后进行doInit()->HeartBeatControlService的初始化
tdm -> tdm : initCache()将redis中的超时时间配置清空，删除缓存中的心跳时间


@enduml
